# Generated by Django 5.2.7 on 2025-10-25 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterUpload',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('filetype', models.CharField(choices=[('xlsx', 'XLSX'), ('xlsb', 'XLSB'), ('csv', 'CSV')], max_length=10)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_rows', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='MasterItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ACT', '행위'), ('DRG', '약제'), ('DX', '진단'), ('ETC', '기타')], default='ACT', max_length=8)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=64, null=True)),
                ('raw_fields', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'unique_together': {('code', 'category')},
            },
        ),
    ]
