# Generated by Django 5.2.7 on 2025-10-29 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField()),
                ('department', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('rrn_masked', models.CharField(blank=True, max_length=20)),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.diagnosiscode')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='clinical.encounter')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DRUG', 'DRUG'), ('PROC', 'PROC')], max_length=8)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('code_drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.drugcode')),
                ('code_proc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.procedurecode')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clinical.encounter')),
            ],
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='clinical.patient'),
        ),
    ]
