# Generated by Django 5.2.7 on 2025-10-24 15:00

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPatient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여'), ('U', '기타')], max_length=1, verbose_name='성별')),
                ('birth_date', models.DateField(verbose_name='생년월일')),
                ('rrn', models.CharField(db_index=True, max_length=14, verbose_name='주민등록번호')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('reg_no', models.CharField(db_index=True, editable=False, max_length=20, verbose_name='등록번호')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical patient',
                'verbose_name_plural': 'historical patients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여'), ('U', '기타')], max_length=1, verbose_name='성별')),
                ('birth_date', models.DateField(verbose_name='생년월일')),
                ('rrn', models.CharField(max_length=14, unique=True, verbose_name='주민등록번호')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='주소')),
                ('reg_no', models.CharField(editable=False, max_length=20, unique=True, verbose_name='등록번호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='patients_pa_name_8d04ea_idx'), models.Index(fields=['reg_no'], name='patients_pa_reg_no_9ac64c_idx'), models.Index(fields=['rrn'], name='patients_pa_rrn_03833a_idx')],
            },
        ),
    ]
