# Generated by Django 5.2.7 on 2025-10-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientregistration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patientregistration',
            new_name='patients_pa_reg_no_69b144_idx',
            old_name='patients_pa_reg_no_hist_idx',
        ),
        migrations.RenameIndex(
            model_name='patientregistration',
            new_name='patients_pa_patient_d8c2cb_idx',
            old_name='patients_pa_patient_issued_idx',
        ),
    ]
