# Generated by Django 5.2.7 on 2025-10-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_externalinfo'),
        ('patients', '0003_rename_patients_pa_reg_no_hist_idx_patients_pa_reg_no_69b144_idx_and_more'),
    ]

    operations = [
    ]
