# Generated by Django 5.2.7 on 2025-10-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_merge_20251027_2158'),
    ]

    operations = []
