# Generated by Django 5.2.7 on 2025-10-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_rename_patients_extdoc_patient_recorded_idx_patients_ex_patient_878714_idx_and_more'),
    ]

    operations = []
