# Generated by Django 5.2.7 on 2025-10-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_rename_patients_extdoc_recorded_idx_patients_ex_patient_878714_idx_and_more'),
    ]

    operations = []
