# Generated by Django 5.2.7 on 2025-10-30 14:25

from django.db import migrations, models


def _ensure_index(apps, schema_editor, model_name, fields, new_name, old_name):
    Model = apps.get_model("patients", model_name)
    table = Model._meta.db_table
    cursor = schema_editor.connection.cursor()
    introspection = schema_editor.connection.introspection
    constraints = introspection.get_constraints(cursor, table)
    if new_name in constraints:
        return
    if old_name in constraints:
        schema_editor.remove_index(Model, models.Index(name=old_name, fields=fields))
        schema_editor.add_index(Model, models.Index(name=new_name, fields=fields))
        return
    schema_editor.add_index(Model, models.Index(name=new_name, fields=fields))


def forwards(apps, schema_editor):
    _ensure_index(
        apps,
        schema_editor,
        model_name="ExternalDocument",
        fields=["patient", "recorded_at"],
        new_name="patients_ex_patient_878714_idx",
        old_name="patients_extdoc_patient_recorded_idx",
    )
    _ensure_index(
        apps,
        schema_editor,
        model_name="ExternalDocument",
        fields=["patient", "created_at"],
        new_name="patients_ex_patient_198ed6_idx",
        old_name="patients_extdoc_patient_created_idx",
    )
    _ensure_index(
        apps,
        schema_editor,
        model_name="ExternalResult",
        fields=["patient", "recorded_at"],
        new_name="patients_ex_patient_1751c0_idx",
        old_name="patients_extres_patient_recorded_idx",
    )
    _ensure_index(
        apps,
        schema_editor,
        model_name="ExternalResult",
        fields=["patient", "created_at"],
        new_name="patients_ex_patient_6f63c5_idx",
        old_name="patients_extres_patient_created_idx",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0007_rename_patients_extdoc_patient_recorded_idx_patients_ex_patient_878714_idx_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(forwards, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="externaldocument",
                    name="patients_extdoc_patient_recorded_idx",
                ),
                migrations.AddIndex(
                    model_name="externaldocument",
                    index=models.Index(
                        name="patients_ex_patient_878714_idx",
                        fields=["patient", "recorded_at"],
                    ),
                ),
                migrations.RemoveIndex(
                    model_name="externaldocument",
                    name="patients_extdoc_patient_created_idx",
                ),
                migrations.AddIndex(
                    model_name="externaldocument",
                    index=models.Index(
                        name="patients_ex_patient_198ed6_idx",
                        fields=["patient", "created_at"],
                    ),
                ),
                migrations.RemoveIndex(
                    model_name="externalresult",
                    name="patients_extres_patient_recorded_idx",
                ),
                migrations.AddIndex(
                    model_name="externalresult",
                    index=models.Index(
                        name="patients_ex_patient_1751c0_idx",
                        fields=["patient", "recorded_at"],
                    ),
                ),
                migrations.RemoveIndex(
                    model_name="externalresult",
                    name="patients_extres_patient_created_idx",
                ),
                migrations.AddIndex(
                    model_name="externalresult",
                    index=models.Index(
                        name="patients_ex_patient_6f63c5_idx",
                        fields=["patient", "created_at"],
                    ),
                ),
            ],
        ),
    ]
