# Generated by Django 5.2.7 on 2025-10-30 14:27

from django.db import migrations, models


def _ensure_index(apps, schema_editor, model_name, fields, new_name, old_name):
    Model = apps.get_model("patients", model_name)
    table = Model._meta.db_table
    cursor = schema_editor.connection.cursor()
    introspection = schema_editor.connection.introspection
    constraints = introspection.get_constraints(cursor, table)
    if new_name in constraints:
        return
    if old_name in constraints:
        schema_editor.remove_index(Model, models.Index(name=old_name, fields=fields))
        schema_editor.add_index(Model, models.Index(name=new_name, fields=fields))
        return
    # Old index is gone; recreate the expected one so query plans remain optimal.
    schema_editor.add_index(Model, models.Index(name=new_name, fields=fields))


def forwards(apps, schema_editor):
    _ensure_index(
        apps,
        schema_editor,
        model_name="ExternalDocument",
        fields=["patient", "recorded_at"],
        new_name="patients_ex_patient_878714_idx",
        old_name="patients_extdoc_patient_recorded_idx",
    )
    _ensure_index(
        apps,
        schema_editor,
        model_name="ExternalDocument",
        fields=["patient", "created_at"],
        new_name="patients_ex_patient_198ed6_idx",
        old_name="patients_extdoc_patient_created_idx",
    )
    _ensure_index(
        apps,
        schema_editor,
        model_name="ExternalResult",
        fields=["patient", "recorded_at"],
        new_name="patients_ex_patient_1751c0_idx",
        old_name="patients_extres_patient_recorded_idx",
    )
    _ensure_index(
        apps,
        schema_editor,
        model_name="ExternalResult",
        fields=["patient", "created_at"],
        new_name="patients_ex_patient_6f63c5_idx",
        old_name="patients_extres_patient_created_idx",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0008_rename_patients_extdoc_patient_recorded_idx_patients_ex_patient_878714_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
