# Generated by Django 5.2.7 on 2025-10-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_rename_patients_extdoc_patient_recorded_idx_patients_ex_patient_878714_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
