# Generated by Django 5.2.7 on 2025-10-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clinicalnote',
            new_name='medical_rec_visit_d_36d20c_idx',
            old_name='visits_clin_visit_d_d75c4a_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicalnote',
            new_name='medical_rec_primary_353108_idx',
            old_name='visits_clin_primary_5819e8_idx',
        ),
    ]
