# Generated by Django 5.2.7 on 2025-10-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_diagnosisentry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='diagnosisentry',
            new_name='medical_rec_note_id_d44cbe_idx',
            old_name='medical_rec_note_code_idx',
        ),
        migrations.RenameIndex(
            model_name='diagnosisentry',
            new_name='medical_rec_code_b637c5_idx',
            old_name='medical_rec_code_idx',
        ),
    ]
