# Generated by Django 5.2.7 on 2025-10-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_auto_add_vitals_anthro_fields'),
        ('medical_records', '0004_rename_medical_rec_note_code_idx_medical_rec_note_id_d44cbe_idx_and_more'),
    ]

    operations = [
    ]
