# Generated by Django 5.2.7 on 2025-10-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_merge_20251027_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvitals',
            name='diastolic',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='이완기 혈압(mmHg)'),
        ),
        migrations.AlterField(
            model_name='historicalvitals',
            name='heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='맥박(bpm)'),
        ),
        migrations.AlterField(
            model_name='historicalvitals',
            name='resp_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='호흡수(/분)'),
        ),
        migrations.AlterField(
            model_name='historicalvitals',
            name='systolic',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='수축기 혈압(mmHg)'),
        ),
    ]
