# Generated by Django 5.2.7 on 2025-10-30 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0009_update_historical_clinicalnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalclinicalnote',
            name='visit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='내원일시'),
        ),
    ]
